import argparse
import json
import os
os.environ.setdefault("OPENCV_IO_ENABLE_OPENEXR", "1")
import shutil
import sys
from pathlib import Path
import re

import cv2
import numpy as np
import requests
import torch
from PIL import Image, ImageEnhance, ImageFilter

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
os.environ.setdefault("MPLCONFIGDIR", "/4T/tmp/matplotlib")
os.environ.setdefault("XDG_CACHE_HOME", "/4T/tmp")

from dataset.foreground_mask_utils import fallback_white_background_mask, load_image_array, resolve_foreground_mask

RAW_ENV_CACHE_DIR = REPO_ROOT / "logs" / "relighting_comparison" / "raw_env_cache"
RAW_ENV_SEARCH_ROOTS = [
    RAW_ENV_CACHE_DIR,
    REPO_ROOT / "demo" / "hdrmaps_for_3d",
    REPO_ROOT / "demo" / "environment_map_sample",
    REPO_ROOT / "validation_data" / "lighting" / "val_preprocessed_environment_resized" / "seen_lighting" / "HDR_raw",
    REPO_ROOT / "validation_data" / "lighting" / "val_preprocessed_environment_resized" / "unseen_lighting" / "HDR_raw",
    REPO_ROOT / "training_data" / "lighting" / "training_lighting_data_subset" / "HDR_raw",
]


def parse_args():
    parser = argparse.ArgumentParser(description="Export aligned assets for relighting comparison figures.")
    parser.add_argument("--manifest", required=True, help="Manifest generated by create_relighting_comparison_manifest.py")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--foreground-background-threshold", type=float, default=0.96)
    parser.add_argument(
        "--method-root",
        action="append",
        default=[],
        help="Method prediction root in the form name=/path/to/root . Expected layout: <root>/<object_id>/pred_image/<target_file>",
    )
    return parser.parse_args()


def parse_method_roots(items):
    parsed = {}
    for item in items:
        if "=" not in item:
            raise ValueError(f"Expected method root in name=path form, got {item}")
        name, path = item.split("=", 1)
        parsed[name.strip()] = Path(path).expanduser()
    return parsed


def load_mask(object_dir: Path, view_idx: int, gt_path: Path, background_threshold: float):
    mask, _ = resolve_foreground_mask(str(object_dir), view_idx=view_idx, reference_image_path=str(gt_path))
    if mask is None:
        rgb = load_image_array(str(gt_path))
        mask = fallback_white_background_mask(rgb, background_threshold=background_threshold)
    mask = np.asarray(mask, dtype=np.float32)
    if mask.ndim == 3:
        mask = mask[..., 0]
    return np.clip(mask, 0.0, 1.0)


def env_name_from_target_file(target_file: str):
    stem = Path(target_file).stem
    match = re.match(r"^\d{3}_\d{3}_(.+)$", stem)
    return match.group(1) if match else stem


def parse_env_variant(env_name: str):
    parts = env_name.split("_")
    flipped = False
    if parts and parts[-1] == "flipped":
        flipped = True
        parts = parts[:-1]

    rotation_deg = None
    if parts and re.fullmatch(r"\d{3}", parts[-1]):
        rotation_deg = int(parts[-1])
        parts = parts[:-1]

    base_name = "_".join(parts)
    return base_name, rotation_deg, flipped


def iter_candidate_raw_paths(env_name: str):
    suffixes = [".exr", ".hdr"]
    for root in RAW_ENV_SEARCH_ROOTS:
        if not root.exists():
            continue
        for suffix in suffixes:
            direct = root / f"{env_name}{suffix}"
            if direct.exists():
                yield direct
            nested = list(root.rglob(f"{env_name}{suffix}"))
            for candidate in nested:
                yield candidate


def find_raw_env_path(env_name: str):
    for candidate in iter_candidate_raw_paths(env_name):
        return candidate
    return None


def parse_polyhaven_size(size_key: str):
    match = re.match(r"^(\d+)", size_key)
    return int(match.group(1)) if match else 10_000


def maybe_download_polyhaven_hdr(base_name: str):
    if not base_name.endswith("_2k"):
        return None

    RAW_ENV_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache_path = RAW_ENV_CACHE_DIR / f"{base_name}.hdr"
    if cache_path.exists():
        return cache_path

    slug = base_name[:-3]
    api_url = f"https://api.polyhaven.com/files/{slug}"
    try:
        payload = requests.get(api_url, timeout=20).json()
    except Exception:
        return None

    hdri = payload.get("hdri", {})
    if not hdri:
        return None

    preferred_sizes = sorted(hdri.keys(), key=parse_polyhaven_size)
    chosen = None
    for size_key in preferred_sizes:
        entry = hdri.get(size_key, {})
        hdr_entry = entry.get("hdr")
        if hdr_entry and size_key == "2k":
            chosen = hdr_entry["url"]
            break
    if chosen is None:
        for size_key in preferred_sizes:
            entry = hdri.get(size_key, {})
            hdr_entry = entry.get("hdr")
            if hdr_entry:
                chosen = hdr_entry["url"]
                break
    if chosen is None:
        return None

    try:
        with requests.get(chosen, stream=True, timeout=120) as response:
            response.raise_for_status()
            with open(cache_path, "wb") as handle:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    if chunk:
                        handle.write(chunk)
    except Exception:
        if cache_path.exists():
            cache_path.unlink()
        return None
    return cache_path


def read_hdr_image(path: Path):
    with open(path, "rb") as handle:
        buffer_ = np.frombuffer(handle.read(), np.uint8)
    bgr = cv2.imdecode(buffer_, cv2.IMREAD_UNCHANGED)
    if bgr is None:
        raise RuntimeError(f"Failed to decode HDR image: {path}")
    if bgr.ndim == 2:
        rgb = np.repeat(bgr[..., None], 3, axis=-1)
    elif bgr.shape[2] == 4:
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGRA2RGB)
    else:
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    return np.asarray(rgb, dtype=np.float32)


def transform_env_variant(env_map: np.ndarray, rotation_deg: int | None, flipped: bool, rotation_sign=1, flip_first=False):
    transformed = np.asarray(env_map, dtype=np.float32)
    if flipped and flip_first:
        transformed = np.flip(transformed, axis=1)
    if rotation_deg:
        shift_px = int(round(transformed.shape[1] * (rotation_deg / 360.0)))
        transformed = np.roll(transformed, rotation_sign * shift_px, axis=1)
    if flipped and not flip_first:
        transformed = np.flip(transformed, axis=1)
    return np.ascontiguousarray(transformed)


def resize_env_for_matching(env_map: np.ndarray, max_width=1024):
    if env_map.shape[1] <= max_width:
        return env_map
    scale = max_width / float(env_map.shape[1])
    out_w = max(int(round(env_map.shape[1] * scale)), 1)
    out_h = max(int(round(env_map.shape[0] * scale)), 1)
    return cv2.resize(env_map, (out_w, out_h), interpolation=cv2.INTER_AREA)


def make_proxy_background(target_lighting_ldr: Image.Image, size):
    bg = target_lighting_ldr.convert("RGB").resize(size, Image.Resampling.BICUBIC)
    bg = bg.filter(ImageFilter.GaussianBlur(10))
    arr = np.asarray(bg, dtype=np.float32)
    arr = arr * 0.82 + np.array([18, 20, 24], dtype=np.float32)
    arr = np.clip(arr, 0, 255).astype(np.uint8)
    return Image.fromarray(arr, mode="RGB")


def get_ray_directions(height: int, width: int, focal_xy):
    jj, ii = np.meshgrid(np.arange(width, dtype=np.float32) + 0.5, np.arange(height, dtype=np.float32) + 0.5)
    cx = width / 2.0
    cy = height / 2.0
    directions = np.stack(
        [
            (jj - cx) / float(focal_xy[0]),
            (ii - cy) / float(focal_xy[1]),
            np.ones_like(jj),
        ],
        axis=-1,
    )
    directions /= np.linalg.norm(directions, axis=-1, keepdims=True).clip(1e-8, None)
    return directions


def get_rays(directions: np.ndarray, c2w: np.ndarray):
    rays_d = directions @ c2w[:3, :3].T
    rays_o = np.broadcast_to(c2w[:3, 3], rays_d.shape)
    return rays_o.reshape(-1, 3), rays_d.reshape(-1, 3)


def get_default_ray_d(size):
    sensor_width = 32.0
    focal_length = 35.0
    resolution_x = size[0]
    resolution_y = size[1]
    focal_length_px = focal_length * resolution_x / sensor_width

    directions = get_ray_directions(resolution_y, resolution_x, [focal_length_px, focal_length_px])
    blender2opencv = np.array([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]], dtype=np.float32)
    w2c = np.load(REPO_ROOT / "demo" / "default_pose.npy")
    w2c = np.vstack([w2c, [0, 0, 0, 1]]).astype(np.float32)
    c2w = np.linalg.inv(w2c) @ blender2opencv
    _, rays_d = get_rays(directions, c2w)
    return rays_d.astype(np.float32)


def sample_env_linear(env_map_np: np.ndarray, size, incident_dir: np.ndarray | None = None):
    env = np.asarray(env_map_np, dtype=np.float32)
    env_t = torch.from_numpy(env)
    envir_map = env_t.permute(2, 0, 1).unsqueeze(0)
    if incident_dir is None:
        incident_dir = get_default_ray_d(size)
    incident_dir = torch.from_numpy(np.asarray(incident_dir, dtype=np.float32))

    phi = torch.arccos(incident_dir[:, 2].clamp(-1.0, 1.0)).reshape(-1) - 1e-6
    theta = torch.atan2(incident_dir[:, 1], incident_dir[:, 0]).reshape(-1)
    query_y = (phi / np.pi) * 2 - 1
    query_x = -theta / np.pi
    grid = torch.stack((query_x, query_y), dim=-1).view(1, size[1], size[0], 2).float().clamp(-1.0 + 1e-6, 1.0 - 1e-6)
    background = torch.nn.functional.grid_sample(envir_map, grid, align_corners=True, mode="bilinear")
    background = background.squeeze(0).permute(1, 2, 0).numpy()
    return background


def sample_env_background(env_map_np: np.ndarray, size, incident_dir: np.ndarray | None = None, apply_gamma=False):
    background = sample_env_linear(env_map_np, size, incident_dir=incident_dir)
    background = np.clip(background, 0.0, 1.0)
    if apply_gamma:
        background = background ** (1 / 2.2)
    background = np.clip(background, 0.0, 1.0)
    return Image.fromarray((background * 255).astype(np.uint8), mode="RGB")


def generate_envir_map_dir(envmap_h: int, envmap_w: int):
    lat_step_size = np.pi / envmap_h
    lng_step_size = 2 * np.pi / envmap_w
    theta, phi = np.meshgrid(
        np.linspace(np.pi / 2 - 0.5 * lat_step_size, -np.pi / 2 + 0.5 * lat_step_size, envmap_h, dtype=np.float32),
        np.linspace(np.pi - 0.5 * lng_step_size, -np.pi + 0.5 * lng_step_size, envmap_w, dtype=np.float32),
        indexing="ij",
    )
    view_dirs = np.stack(
        [
            np.cos(phi) * np.cos(theta),
            np.sin(phi) * np.cos(theta),
            np.sin(theta),
        ],
        axis=-1,
    ).reshape(-1, 3)
    return view_dirs.astype(np.float32)


def render_rotated_lighting_map(env_map_np: np.ndarray, target_rt: np.ndarray, output_size):
    env_h, env_w = env_map_np.shape[:2]
    view_dirs = generate_envir_map_dir(env_h, env_w)
    axis_aligned_transform = np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]], dtype=np.float32)
    axis_aligned_r = axis_aligned_transform @ target_rt[:3, :3]
    view_dirs_world = view_dirs @ axis_aligned_r
    lighting = sample_env_linear(env_map_np, (env_w, env_h), incident_dir=view_dirs_world)
    lighting = np.clip(lighting, 0.0, 1.0) ** (1 / 2.2)
    lighting_img = Image.fromarray((lighting * 255).astype(np.uint8), mode="RGB").resize(output_size, Image.Resampling.BILINEAR)
    return np.asarray(lighting_img, dtype=np.float32) / 255.0


def load_best_raw_env(sample: dict, target_lighting_ldr: Image.Image, target_rt: np.ndarray):
    env_name = env_name_from_target_file(sample["target_file"])

    exact_path = find_raw_env_path(env_name)
    if exact_path is not None:
        return read_hdr_image(exact_path)

    base_name, rotation_deg, flipped = parse_env_variant(env_name)
    base_path = find_raw_env_path(base_name)
    if base_path is None:
        base_path = maybe_download_polyhaven_hdr(base_name)
    if base_path is None:
        return None

    base_env = read_hdr_image(base_path)
    if rotation_deg is None and not flipped:
        return base_env

    target_arr = np.asarray(target_lighting_ldr.convert("RGB"), dtype=np.float32) / 255.0
    candidate_specs = []
    if rotation_deg is None:
        candidate_specs.append((1, False))
    elif not flipped:
        candidate_specs.append((1, False))
        candidate_specs.append((-1, False))
    else:
        for rotation_sign in (1, -1):
            for flip_first in (False, True):
                candidate_specs.append((rotation_sign, flip_first))

    matching_env = resize_env_for_matching(base_env)
    best_spec = None
    best_score = float("inf")
    for rotation_sign, flip_first in candidate_specs:
        candidate = transform_env_variant(
            matching_env,
            rotation_deg,
            flipped,
            rotation_sign=rotation_sign,
            flip_first=flip_first,
        )
        rendered = render_rotated_lighting_map(candidate, target_rt, target_lighting_ldr.size)
        score = float(np.mean((rendered - target_arr) ** 2))
        if score < best_score:
            best_score = score
            best_spec = (rotation_sign, flip_first)

    if best_spec is None:
        return base_env

    return transform_env_variant(
        base_env,
        rotation_deg,
        flipped,
        rotation_sign=best_spec[0],
        flip_first=best_spec[1],
    )


def make_display_background(target_lighting_ldr: Image.Image, size, sample: dict, object_dir: Path):
    rt_path = object_dir / f"{sample['view_idx']:03d}_RT.npy"
    target_rt = np.load(rt_path) if rt_path.exists() else None
    if target_rt is not None:
        raw_env = load_best_raw_env(sample, target_lighting_ldr, target_rt)
        if raw_env is not None:
            return sample_env_background(raw_env, size, apply_gamma=True)

    bg = sample_env_background(np.asarray(target_lighting_ldr.convert("RGB"), dtype=np.float32) / 255.0, size)
    bg = bg.filter(ImageFilter.UnsharpMask(radius=1.0, percent=140, threshold=2))
    bg = ImageEnhance.Contrast(bg).enhance(1.04)
    return bg


def make_perspective_background(target_lighting_ldr: Image.Image, size):
    env = np.asarray(target_lighting_ldr.convert("RGB"), dtype=np.float32) / 255.0
    h, w = env.shape[:2]
    lum = 0.299 * env[..., 0] + 0.587 * env[..., 1] + 0.114 * env[..., 2]
    bright_y, bright_x = np.unravel_index(np.argmax(lum), lum.shape)
    yaw0 = (bright_x / max(w - 1, 1)) * 2.0 * np.pi - np.pi
    pitch0 = np.pi / 2.0 - (bright_y / max(h - 1, 1)) * np.pi

    out_h, out_w = size[1], size[0]
    fov = np.deg2rad(92.0)
    xs = np.linspace(-np.tan(fov / 2.0), np.tan(fov / 2.0), out_w, dtype=np.float32)
    ys = np.linspace(-np.tan(fov / 2.0), np.tan(fov / 2.0), out_h, dtype=np.float32)
    xx, yy = np.meshgrid(xs, ys)
    dirs = np.stack([xx, -yy, np.ones_like(xx)], axis=-1)
    dirs /= np.linalg.norm(dirs, axis=-1, keepdims=True).clip(1e-8, None)

    cy, sy = np.cos(yaw0), np.sin(yaw0)
    cp, sp = np.cos(pitch0), np.sin(pitch0)
    rot_y = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]], dtype=np.float32)
    rot_x = np.array([[1, 0, 0], [0, cp, -sp], [0, sp, cp]], dtype=np.float32)
    dirs = dirs @ rot_x.T
    dirs = dirs @ rot_y.T

    lon = np.arctan2(dirs[..., 0], dirs[..., 2])
    lat = np.arcsin(np.clip(dirs[..., 1], -1.0, 1.0))
    u = (lon + np.pi) / (2.0 * np.pi) * (w - 1)
    v = (np.pi / 2.0 - lat) / np.pi * (h - 1)
    ui = np.clip(np.round(u).astype(np.int32), 0, w - 1)
    vi = np.clip(np.round(v).astype(np.int32), 0, h - 1)
    bg = env[vi, ui]
    bg = np.clip(bg ** (1 / 1.6), 0, 1)
    return Image.fromarray((bg * 255).astype(np.uint8), mode="RGB")


def composite_on_background(image: Image.Image, background: Image.Image, mask: np.ndarray):
    image = image.convert("RGB").resize(background.size, Image.Resampling.BICUBIC)
    alpha_img = Image.fromarray((np.clip(mask, 0.0, 1.0) * 255).astype(np.uint8), mode="L").resize(
        background.size, Image.Resampling.BILINEAR
    )
    alpha_img = alpha_img.filter(ImageFilter.GaussianBlur(0.8))

    fg = np.asarray(image, dtype=np.float32) / 255.0
    bg = np.asarray(background.convert("RGB"), dtype=np.float32) / 255.0
    alpha = np.asarray(alpha_img, dtype=np.float32) / 255.0
    alpha = np.clip(alpha, 0.0, 1.0)[..., None]

    # Remove white-background contamination before compositing.
    fg_decontaminated = np.clip((fg - (1.0 - alpha)) / np.clip(alpha, 1e-3, 1.0), 0.0, 1.0)
    comp = fg_decontaminated * alpha + bg * (1.0 - alpha)
    return Image.fromarray((comp * 255).astype(np.uint8), mode="RGB")


def resolve_method_prediction(method_root: Path, object_id: str, target_file: str):
    candidates = [
        method_root / object_id / "pred_image" / target_file,
        method_root / object_id / target_file,
        method_root / target_file,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def main():
    args = parse_args()
    manifest = json.loads(Path(args.manifest).read_text(encoding="utf-8"))
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    method_roots = parse_method_roots(args.method_root)

    exported_samples = []
    for sample in manifest["samples"]:
        object_id = sample["object_id"]
        sample_dir = output_dir / f"{sample['preset']}_{object_id}_v{sample['view_idx']:03d}_t{sample['target_lighting_index']:03d}"
        sample_dir.mkdir(parents=True, exist_ok=True)

        input_path = Path(sample["input_path"])
        gt_path = Path(sample["gt_path"])
        target_ldr_path = Path(sample["target_lighting_ldr_path"])
        object_dir = gt_path.parent

        input_image = Image.open(input_path).convert("RGB")
        gt_image = Image.open(gt_path).convert("RGB")
        target_ldr = Image.open(target_ldr_path).convert("RGB")
        mask = load_mask(object_dir, sample["view_idx"], gt_path, args.foreground_background_threshold)
        proxy_bg = make_proxy_background(target_ldr, gt_image.size)
        projected_bg = make_perspective_background(target_ldr, gt_image.size)
        display_bg = make_display_background(target_ldr, gt_image.size, sample, object_dir)
        gt_composite = composite_on_background(gt_image, display_bg, mask)

        shutil.copy2(input_path, sample_dir / "input.png")
        shutil.copy2(gt_path, sample_dir / "ground_truth_white_bg.png")
        shutil.copy2(target_ldr_path, sample_dir / "target_lighting.png")
        proxy_bg.save(sample_dir / "target_background_proxy.png")
        projected_bg.save(sample_dir / "target_background_projected.png")
        display_bg.save(sample_dir / "target_background.png")
        gt_composite.save(sample_dir / "ground_truth_composited.png")
        Image.fromarray((mask * 255).astype(np.uint8), mode="L").save(sample_dir / "foreground_mask.png")

        exported = dict(sample)
        exported["sample_dir"] = str(sample_dir)
        exported["input_export"] = str(sample_dir / "input.png")
        exported["ground_truth_export"] = str(sample_dir / "ground_truth_composited.png")
        exported["target_lighting_export"] = str(sample_dir / "target_lighting.png")
        exported["background_export"] = str(sample_dir / "target_background.png")
        exported["background_projected_export"] = str(sample_dir / "target_background_projected.png")
        exported["methods"] = {}

        for method_name, method_root in method_roots.items():
            pred_path = resolve_method_prediction(method_root, object_id, sample["target_file"])
            if pred_path is None:
                continue
            pred_image = Image.open(pred_path).convert("RGB")
            composited = composite_on_background(pred_image, display_bg, mask)
            shutil.copy2(pred_path, sample_dir / f"{method_name}_white_bg.png")
            composited.save(sample_dir / f"{method_name}_composited.png")
            exported["methods"][method_name] = {
                "source": str(pred_path),
                "composited": str(sample_dir / f"{method_name}_composited.png"),
            }

        exported_samples.append(exported)

    out_manifest = {
        "source_manifest": args.manifest,
        "samples": exported_samples,
    }
    out_path = output_dir / "exported_assets_manifest.json"
    out_path.write_text(json.dumps(out_manifest, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
